
install.packages('ggplot2', dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages('RODBCext', dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages('shinythemes', dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages('RODBC', dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages('DT', dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages('shinyjs', dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages('shinyWidgets', dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages('dplyr', dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages('reshape', dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages('viridis', dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages('wesanderson', dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages('plotly', dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages('shinyBS', dependencies=TRUE, repos='http://cran.rstudio.com/')
