-----------------------------------
 -- CREATE THE DIMENSION TABLES --
-----------------------------------

CREATE TABLE DIM_AGENT (
    AGENT_ID NUMBER NOT NULL UNIQUE,
    AGENT_NAME VARCHAR2(100) NOT NULL
);

CREATE TABLE DIM_WORK_KPI (
    KPI_ID NUMBER UNIQUE,
    TYPE_DESC VARCHAR2(100) NOT NULL
);

CREATE TABLE DIM_CITY (
    CITY_ID NUMBER UNIQUE,
    CITY_NAME VARCHAR2(100) NOT NULL
);

CREATE TABLE DIM_SHIFTS (
    SHIFT_ID NUMBER UNIQUE,
    SHIFT_TYPE VARCHAR2(100) NOT NULL
);

CREATE TABLE DIM_WEEKS (
    WEEK_ID NUMBER UNIQUE,
    WEEK_DAY VARCHAR2(100) NOT NULL
);

-----------------------------------
 -- CREATE THE STAGING TABLES --
-----------------------------------


TRUNCATE TABLE STAGING_NOBLE;
TRUNCATE TABLE STAGING_FILES_READ;

CREATE TABLE STAGING_NOBLE (
    AGENT_NAME     VARCHAR2(30),
    CODE           VARCHAR2(30),
    CONTACT_DATE   DATE,
    LOGON_TIME     VARCHAR2(30),
    LOGOFF_TIME    VARCHAR2(30),
    CONNECTED      VARCHAR2(30),
    WAITING        VARCHAR2(30),
    PAUSED         VARCHAR2(30),
    DEASSIGN       VARCHAR2(30),
    ACW            VARCHAR2(30),
    TOTAL          VARCHAR2(30),
    FILE_NAME      VARCHAR2(100),
    LOAD_DATE      TIMESTAMP DEFAULT SYSDATE    
);

CREATE TABLE STAGING_FILES_READ (

    FILE_NAME VARCHAR2(50)

);

-----------------------------------
 -- CREATE THE JOBS TABLES --
-----------------------------------

 CREATE SEQUENCE  JOB_SEQ  MINVALUE 1 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;


CREATE TABLE JOBS_SCHEDULE (
ID NUMBER,
START_DATE      TIMESTAMP DEFAULT SYSDATE,   
END_DATE        TIMESTAMP DEFAULT SYSDATE,
DESCRIPTIONS    VARCHAR2(3000));


