UPDATE DAILY_NOBLE_DATA
SET
    FLAG = 'S' WHERE ID IN (
SELECT
      ND1.ID
FROM
    DAILY_NOBLE_DATA   ND1
    INNER JOIN DAILY_NOBLE_DATA   ND2 ON ND1.AGENT_NAME = ND2.AGENT_NAME
WHERE
    TO_NUMBER(REPLACE(ND1.LOGON_TIME, ':', '')) - TO_NUMBER(REPLACE(ND2.LOGOFF_TIME, ':', '')) > 120000);
    
COMMIT;



CREATE TABLE FACT_DAILY_CALLS AS 

SELECT -- AGENT NAME
       -- KPIS,
       -- SHIFT,
       -- VALUE
       FROM 